name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Create and populate config.json file
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cat <<EOF > config.json
          {
              "DISCORD_TOKEN": "$DISCORD_TOKEN",
              "DISCORD_CLIENT_ID": "$DISCORD_CLIENT_ID",
              "DISCORD_GUILD_ID": "$DISCORD_GUILD_ID",
              "OPENAI_API_KEY": "$OPENAI_API_KEY"
          }
          EOF

      - name: Build image 
        run: docker build -t ai-stuff-registry/ai-toolbox-bot .

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Tag image 
        run: docker tag ai-stuff-registry/ai-toolbox-bot registry.digitalocean.com/ai-stuff-registry/ai-toolbox-bot:latest

      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/ai-stuff-registry/ai-toolbox-bot:latest

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ai_toolbox_bot_droplet.key
          chmod 600 ~/.ssh/id_ai_toolbox_bot_droplet.key

          export SSH_USER="ai-toolbox-bot"
          export SSH_HOST="$(doctl compute droplet get ai-toolbox-bot-droplet --template {{.PublicIPv4}})"

          cat <<EOF > ~/.ssh/config
          Host ai-toolbox-bot-droplet
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_ai_toolbox_bot_droplet.key
            StrictHostKeyChecking no
          EOF

      - name: Stop ai-toolbox-bot service
        run: ssh ai-toolbox-bot-droplet 'sudo systemctl stop ai-toolbox-bot'

      - name: Start ai-toolbox-bot service
        run: ssh ai-toolbox-bot-droplet 'sudo systemctl start ai-toolbox-bot'

